import React from 'react';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <style jsx>
        {`  
          main{
            animation: fadein 2s;
          }
          h1 {
            display: inline-flex;
            justify-content: center;
            align-items: center;
            white-space: pre-wrap;
            color: white;
            padding: 10px;
            text-align: center;
            font-size: 50px;
            font-weight: bolder;
          }
        `}
      </style>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          {'Gomi의 NextJS Code Kata\n(그 카타 아님)'}
        </h1>
      </main>
    </>
  );
}
