#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 현재 브렌치의 네임을 branch에 저장
branch="$(git rev-parse --abbrev-ref HEAD)"

# branch가 main이라면 문구를 노출 시키며 종료
if [ "$branch" = "main" ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi

echo "허스키 실행..."
npm run lint
npm test
npm run build